version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    container_name: 'postgres'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - /mnt/explorer_new_extra_disk_1/postgres-data:/var/lib/postgresql/data
    ports:
      - 7432:5432

  blockscout:
    depends_on:
      - db
#      - smart-contract-verifier
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    restart: always
    container_name: 'blockscout'
    links:
      - db:database
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout.env
    ports:
      - 4000:4000
    labels:
      - "autoheal=true"
    healthcheck:
      test: curl --fail http://localhost:4000/ || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s

  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    restart: always
    environment:
      - AUTOHEAL_INTERVAL=60
      - AUTOHEAL_START_PERIOD=300
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  smart-contract-verifier:
    image: ghcr.io/blockscout/smart-contract-verifier:${SMART_CONTRACT_VERIFIER_DOCKER_TAG:-latest}
    restart: always
    container_name: 'smart-contract-verifier'
    env_file:
      -  ./envs/common-smart-contract-verifier.env
    ports:
      - 8043:8043
